// wilbur-svelte/src/lib/components/ui/ToastContainer.svelte
<script lang="ts">
	import { toastStore, type Toast } from '$lib/stores';
	import { X, CheckCircle, AlertCircle, AlertTriangle, Info } from 'lucide-svelte';
	import { fly } from 'svelte/transition';

	function getIcon(type: Toast['type']) {
		switch (type) {
			case 'success':
				return { icon: CheckCircle, class: 'text-green-400' };
			case 'error':
				return { icon: AlertCircle, class: 'text-red-400' };
			case 'warning':
				return { icon: AlertTriangle, class: 'text-yellow-400' };
			case 'info':
			default:
				return { icon: Info, class: 'text-blue-400' };
		}
	}

	function getBgClass(type: Toast['type']): string {
		switch (type) {
			case 'success':
				return 'bg-green-500/10 border-green-500/30';
			case 'error':
				return 'bg-red-500/10 border-red-500/30';
			case 'warning':
				return 'bg-yellow-500/10 border-yellow-500/30';
			case 'info':
			default:
				return 'bg-blue-500/10 border-blue-500/30';
		}
	}
</script>

<div class="fixed bottom-4 right-4 z-[100] flex flex-col gap-2 pointer-events-none">
	{#each toastStore.toasts as toast (toast.id)}
		{@const iconStyle = getIcon(toast.type)}
		<div
			class="pointer-events-auto flex items-start gap-3 rounded-xl border {getBgClass(toast.type)} bg-surface-800 p-4 shadow-xl backdrop-blur max-w-sm"
			in:fly={{ x: 100, duration: 200 }}
			out:fly={{ x: 100, duration: 150 }}
		>
			<div class="flex-shrink-0">
				<iconStyle.icon class="h-5 w-5 {iconStyle.class}" />
			</div>

			<div class="flex-1 min-w-0">
				{#if toast.title}
					<h4 class="font-medium text-white">{toast.title}</h4>
				{/if}
				<p class="text-sm text-surface-300 {toast.title ? 'mt-0.5' : ''}">{toast.message}</p>
			</div>

			{#if toast.dismissible}
				<button
					onclick={() => toastStore.dismiss(toast.id)}
					class="flex-shrink-0 rounded-lg p-1 text-surface-400 hover:bg-surface-700 hover:text-white transition"
				>
					<X class="h-4 w-4" />
				</button>
			{/if}
		</div>
	{/each}
</div>

// src/components/ToastContainer.tsx
/**
 * ===============================================================
 * ToastContainer.tsx
 * ---------------------------------------------------------------
 * Renders all toast messages from the toastStore.
 * Smooth Fluent fade-in/out animations via Tailwind.
 * ===============================================================
 */

import { motion, AnimatePresence } from "framer-motion";
import { CheckCircle, AlertCircle, Info, XCircle, X } from "lucide-react";

import { useToastStore } from "../store/toastStore";

export function ToastContainer() {
  const { toasts, removeToast } = useToastStore();

  const getTypeStyles = (type: string) => {
    switch (type) {
      case 'success':
        return {
          bg: 'bg-green-900/90',
          border: 'border-green-700',
          iconColor: 'text-green-400',
          Icon: CheckCircle,
        };
      case 'error':
        return {
          bg: 'bg-red-900/90',
          border: 'border-red-700',
          iconColor: 'text-red-400',
          Icon: XCircle,
        };
      case 'warning':
        return {
          bg: 'bg-yellow-900/90',
          border: 'border-yellow-700',
          iconColor: 'text-yellow-400',
          Icon: AlertCircle,
        };
      case 'info':
      default:
        return {
          bg: 'bg-blue-900/90',
          border: 'border-blue-700',
          iconColor: 'text-blue-400',
          Icon: Info,
        };
    }
  };

  return (
    <div className="fixed bottom-4 right-4 z-[9999] flex flex-col gap-3">
      <AnimatePresence>
        {toasts.map((toast) => {
          const styles = getTypeStyles(toast.type);
          const Icon = styles.Icon;

          return (
            <motion.div
              key={toast.id}
              initial={{ opacity: 0, x: 100 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 100 }}
              transition={{ duration: 0.25 }}
              className={`
                ${styles.bg} ${styles.border}
                border backdrop-blur-sm px-4 py-3 rounded-lg shadow-lg text-white
                flex items-center gap-3
              `}
            >
              <Icon className={`w-5 h-5 ${styles.iconColor}`} />
              <span className="text-sm font-medium flex-1 text-white">{toast.message}</span>
              <button
                onClick={() => removeToast(toast.id)}
                className="p-1 rounded hover:bg-white/10 transition-colors"
                aria-label="Close notification"
              >
                <X className="w-4 h-4 text-slate-400 hover:text-white" />
              </button>
            </motion.div>
          );
        })}
      </AnimatePresence>
    </div>
  );
}
